Add nesseccery scripts
TouchInstinct/BuildScripts pull request #134
Opened 2019-08-01 20:52 UTC by SoriUR

2019-08-02 09:07 UTC, petropavel13 requested changes

2019-08-02 09:07 UTC, petropavel13 commented on xcode/UnusedConfig.txt
> +--ignored-resources:
use yaml format?

2019-08-02 09:07 UTC, petropavel13 commented on xcode/build_phases/Unused.rb
> +          if item == $config_argv_key
use https://docs.ruby-lang.org/en/2.1.0/OptionParser.html instead?

2019-08-02 14:35 UTC, petropavel13 requested changes

2019-08-02 14:35 UTC, petropavel13 commented on xcode/UnusedConfig.yml
> +--ignored-resources:
`--` is legal in yaml?

2019-08-02 14:35 UTC, petropavel13 commented on xcode/build_phases/Unused.rb
> +            puts "---------\n Warning: Config file is now provided \n---------"
not?

2019-08-02 14:35 UTC, petropavel13 commented on xcode/UnusedConfig.yml
> +--ignored-resources:
do like swiftlint:
https://gist.github.com/tweetjay/1b7f00b6f312a5a2cf7b5676420b9b0c#file-swiftlint-yml-L3

2019-08-02 15:36 UTC, petropavel13 submitted a review, later dismissed

2019-08-02 16:40 UTC, petropavel13 submitted a review, later dismissed

2019-08-05 10:20 UTC, Viveron approved these changes

2019-08-05 10:21 UTC, petropavel13 approved these changes

2019-08-05 10:25 UTC, merged