Create gradle kotlin plugins for Static Analysis and Api Generator
TouchInstinct/BuildScripts pull request #223
Opened 2020-08-20 15:29 UTC by maxbach

## Причины:
1. Плагины позволяют быть более гибкими в настройки дополнительного функционала в градле.
2. В плагинах можно настроить более жесткое апи для настройки с помощью extensions
3. Скрипты на языке Kotlin более читаемые, чем на Groovy
4. Многомодульные проекты не работали со старыми скриптами. 

## Дополнительные изменения
1. Удалены ненужные файлы
2. Градл скрипты перенесены в папку gradle/scripts

## Как мигрировать проект:
1. В settings.gradle или settings.gradle.kts настроить блок pluginManagement
``` kotlin
pluginManagement {
    repositories {
        google()
        jcenter()
        gradlePluginPortal()
    }
}
```
2. В settings.gradle или settings.gradle.kts добавить модуль с плагинами в сборку
``` kotlin
includeBuild("BuildScripts/gradle/plugins")
```
3. Добавить плагины в проекты через блок plugins. StaticAnalysis нужно добавить в root project. ApiGenerator нужно добавить в тот проект, в который нужно генерировать классы.
``` kotlin
plugins {
    id("static-analysis-android")
    id("static-analysis-backend")
    id("api-generator-android")
    id("api-generator-backend")
}
```
4. Настроить с помощью extension staticAnalysis или apiGenerator в том проекте, где добавили плагин
```kotlin
apiGenerator {    
    pathToApiSchemes = "/Project-common/api"
    outputPackageName = "ru.touchin.project"
    outputLanguage = apigen.OutputLanguage.KotlinAndroid(
            methodOutputType = apigen.MethodOutputType.Coroutine
    )
}
```
```kotlin
staticAnalysis {
    buildScriptDir = "BuildScripts/"
}
```
## Примеры миграции
- [Монета-андроид](https://github.com/TouchInstinct/Runtime-android/pull/146)
- [Лукойл-андроид](https://github.com/TouchInstinct/Licard-android/pull/1259)

2020-08-21 07:36 UTC, vender98 submitted a review, later dismissed

2020-08-21 07:36 UTC, vender98 commented on gradle/plugins/src/main/java/static_analysis/utils/Extensions.kt
> +fun Project.getSources(excludes: String): FileTree = files(
Может имеет смысл разделить экстеншены для соответствующих классов в отдельные файлы ?
Ну на случай, если это в будущем потенциально может превратиться в помойку экстеншенов для всего подряд.

2020-08-21 07:36 UTC, vender98 commented on gradle/plugins/src/main/java/static_analysis/utils/Extensions.kt
> +fun xmlParser(file: File) = XmlParser().parse(file)
Это не extension. Может лучше для такого что-то типа XmlUtils.kt ?

2020-08-21 07:36 UTC, vender98 commented on gradle/plugins/src/main/java/static_analysis/linters/AndroidLinter.kt
> +                    task.name.contains(buildType!!, ignoreCase = true) && task.name.contains("lint")
`buildType!!` потенциально может упасть ?
Не замечаю выше где предусматривается обработка для кейса когда он null

2020-08-24 23:41 UTC, vladimirshefer requested changes

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorAndroidPlugin.kt
> +                        }
опционально тут и ниже

многострочные лямбды с именованным параметром либо сделать в одну строчку

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorAndroidPlugin.kt
> +    private fun Project.getDirectoryForGeneration() = file("$buildDir/generated/api")
тут ведь не обязательно такой пакет будет?

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorBackendPlugin.kt
> +        with(target) {
может не нужно with?
все переменные и функции ниже непонятно какие явщяютcя extension а какие нет

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorBackendPlugin.kt
> +            val extension = getExtension()
можно тогда прямо target.getExtension запихать внутрь with

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorBackendPlugin.kt
> +        with(target) {
просто with хорошо работает когда внутри лямбды 90% строчек кода - это поля\методы целевого объекта. а если target юзасется один раз - то with лишний

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorBackendPlugin.kt
> +        with(target) {
опционально

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/apigen/ApiGeneratorPlugin.kt
> +        const val API_GENERATOR_VERSION = "1.4.0-beta5"
может позволить это указывать через настройки?

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/utils/Extensions.kt
> +fun Project.getSources(excludes: String): FileTree = files(
+1
боль от помоек с экстеншнами можно наблюдать на апигенераторе

2020-08-24 23:41 UTC, vladimirshefer commented on static_analysis_configs/detekt-config.yml
> +  active: false
странное изменение
ошибка или есть смысл?

2020-08-24 23:41 UTC, vladimirshefer commented on static_analysis_configs/lint.xml
> +    <!-- DISABLE RULES BELOW -->
это тудушка такая?

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/utils/ReportGenerator.kt
> +                .map { it.first.name to it.second.size }
тут читабельнее применить Destructuring Declaration c хорошими именами для first и second

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/utils/ReportGenerator.kt
> +                .map { it.second }
convert lambda to reference

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/utils/ReportGenerator.kt
> +    }
Экстеншны должны быть логичным продолжением стандартного набора методов.

Предалаю у StringBuilder.* сделать "convert receiver to parameter"

2020-08-24 23:41 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/linters/CpdLinter.kt
> +            .map { it.path }
convert lambda to reference

2020-09-08 12:20 UTC, maxbach commented on gradle/plugins/src/main/java/apigen/ApiGeneratorAndroidPlugin.kt
> +    private fun Project.getDirectoryForGeneration() = file("$buildDir/generated/api")
Для Android обязательный

2020-09-08 12:21 UTC, maxbach commented on gradle/plugins/src/main/java/apigen/ApiGeneratorBackendPlugin.kt
> +            val extension = getExtension()
Убрал with

2020-09-08 12:28 UTC, maxbach commented on gradle/plugins/src/main/java/apigen/ApiGeneratorPlugin.kt
> +        const val API_GENERATOR_VERSION = "1.4.0-beta5"
Лучше не надо
1. Пользователь выберет старую версию, на которой плагин может сломаться
2. Особенности gradle не позволит это сделать без костылей, так как настройка зависимостей проходит после того, как extension будет настроен

2020-09-08 12:30 UTC, maxbach commented on static_analysis_configs/detekt-config.yml
> +  active: false
Этот флаг выключает console-report в detekt. Нужно для того, чтобы сделать почище вывод в консоль. Данные при включенном флаге дублируются, так как в отчете нашего плагина будет все прописано

2020-09-08 12:30 UTC, maxbach commented on static_analysis_configs/lint.xml
> +    <!-- DISABLE RULES BELOW -->
Легаси. Потом исправим, когда новый кодстайл применим

2020-09-08 12:33 UTC, maxbach commented on gradle/plugins/src/main/java/static_analysis/utils/ReportGenerator.kt
> +    }
Не вижу проблемы, если extensions приватные

2020-09-08 14:27 UTC, vladimirshefer commented on static_analysis_configs/lint.xml
> +    <!-- DISABLE RULES BELOW -->
не понимаю как ответ связан с вопросом.
легаси чего?
я спрашиваю это TODO?
почему не удалить сейчас?

2020-09-08 14:27 UTC, vladimirshefer commented on static_analysis_configs/lint.xml
> +    <!-- DISABLE RULES BELOW -->
легаси всмысле что это не ты панисал а просто перенес из старого кода?

2020-09-08 14:50 UTC, vladimirshefer requested changes

2020-09-08 14:50 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/utils/XmlUtils.kt
> +import groovy.util.XmlParser
пакет исчез. вернуть

2020-09-08 14:50 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/linters/AndroidLinter.kt
> +        if (buildType == null) throw IllegalStateException("build type must not be null in android linter")
Add braces to if statement

2020-09-08 14:50 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/linters/AndroidLinter.kt
> +        if (buildType == null) throw IllegalStateException("build type must not be null in android linter")
Exception message should start with capital letter

2020-09-08 14:50 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/linters/AndroidLinter.kt
> +        if (buildType == null) throw IllegalStateException("build type must not be null in android linter")
опицонально: можно заменить на элвис

2020-09-08 14:50 UTC, vladimirshefer commented on gradle/plugins/src/main/java/static_analysis/linters/AndroidLinter.kt
> +                    }?.path
Правило 25
При переносе на новую строку цепочки вызова методов символ . или оператор ?. переносятся на следующую строку, property при этом разрешается оставлять на одной строке

2020-09-08 15:57 UTC, maxbach commented on static_analysis_configs/lint.xml
> +    <!-- DISABLE RULES BELOW -->
Ага. Перенес из старого кода

2020-09-09 10:34 UTC, vladimirshefer approved these changes

2020-09-10 08:49 UTC, vender98 approved these changes

2020-09-11 15:25 UTC, merged